version: '3'
services:

  mysqlDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:3306
    volumes:
      - mysqlDB:/var/lib/mysql
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
      image: phpmyadmin
      ports:
        - 8083:80
      environment:
        - PMA_ARBITRARY=1

  rabbitmq:
      image: rabbitmq:management
      ports:
        - "5672:5672"
        - "15672:15672"
      env_file:
        - docker.env

  redis:
    image: redis:alpine
    ports:
      - 6379:6379 
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis

volumes:
  mysqlDB: