version: '3'
services:

  mysqlDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - docker.env
    ports:
      - 3309:3306
    volumes:
      - mysqlDB:/var/lib/mysql


  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8083:80
      environment:
        - PMA_ARBITRARY=1

  rabbitmq:
      image: rabbitmq:management

      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
      env_file:
        - docker.env

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379 

    volumes:
          - ./redis/data:/data

  # gateway:
  #   build:
  #     context: ./server/gateway
  #     dockerfile: Dockerfile
  #   container_name: gateway
  #   ports:
  #       - "3002:3000"
  #   command: npm run start
volumes:
  mysqlDB: